services:
  angular:
    build:
      context: ./frontend/
    volumes:
      - ./frontend/AngularApp:/app
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  flask:
    build:
      context: ./backend/
    volumes:
      - ./backend:/app
    ports:
      - '5001:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

