services:
  angular:
    container_name: angular
    build:
      context: ./frontend/
    volumes:
      - ./frontend/AngularApp:/app
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  flask:
    container_name: flask
    build:
      context: ./backend/
    volumes:
      - ./backend:/app
    ports:
      - '5001:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    networks:
            - appnet

  postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - '6060:5432'
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - appnet

volumes:
    data:
      name: postgres-volume

networks:
    appnet:

