services:
  angular:
    container_name: angular-dev
    image: matcha/dev-angular
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/AngularApp:/app
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  flask:
    container_name: flask-dev
    image: matcha/dev-flask
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - '5001:5000'
    environment:
      - FLASK_APP=matcha
      - FLASK_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: flask --debug run --host=0.0.0.0 --port=5000
    depends_on:
      - postgres
    networks:
            - appnet

  postgres:
    container_name: postgres-dev
    image: postgres:latest
    ports:
        - '6543:5432'
    volumes:
        - data:/var/lib/postgresql/data
        - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_NAME}
    networks:
        - appnet

volumes:
    data:
      name: postgres-volume-dev

networks:
    appnet:
